// export interface Product {
//  slug: string;
//   name: string;
//   brand: string;
//   price: number;
//   oldPrice?: number;
//   image: string;       // main image for grid
//   images: string[];    // gallery images
//   description: string;
//   details: string[];
//   category: string;
//   categoryId: string;
// }

// export const products: Product[] = [
//   {
//     slug: "modern-wooden-chair-c",    name: "Modern Wooden Chair",
//     price: 120,
//     brand: "WoodWorks",
//     oldPrice: 150,
//     image: "/assets/chair1.jpg",
//     images: ["/assets/chair1.jpg", "/assets/chair2.jpg", "/assets/chair3.jpg"],
//     description: "A stylish modern wooden chair perfect for living room setups.",
//     details: ["Made from Oak wood", "Ergonomic design", "Polished finish"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-a",    name: "Classic Leather Sofa",
//     brand: "ComfortHaus",
//     price: 540,
//     oldPrice: 600,
//     image: "/assets/chair10.jpg",
//     images: ["/assets/chair10.jpg", "/assets/chair11.jpg", "/assets/chair12.jpg"],
//     description: "Luxurious leather sofa to elevate your living space.",
//     details: ["Genuine leather", "Seating for 3", "Durable frame"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-b",    name: "Upholstered Bed Frame",
//     brand: "LuxHome",
//     price: 990,
//     image: "/assets/chair8.jpg",
//     images: ["/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair10.jpg"],
//     description: "Comfortable bed frame with a chic upholstered finish.",
//     details: ["King size", "Soft headboard", "Sturdy design"],
//     category: "Bedroom",
//   },
//   {
//     slug: "modern-wooden-chair-e",    name: "Velvet Lounge Chair",
//     brand: "LuxHome",
//     price: 320,
//     oldPrice: 400,
//     image: "/assets/chair8.jpg",
//     images: ["/assets/chair8.jpg", "/assets/chair9.jpg"],
//     description: "Elegant velvet chair to add luxury to your living room.",
//     details: ["Velvet finish", "Soft cushioning", "Solid wooden legs"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-f",    name: "Oak Dining Set",
//     brand: "NordCraft",
//     price: 780,
//     image: "/assets/chair4.jpg",
//     images: ["/assets/chair4.jpg", "/assets/chair5.jpg"],
//     description: "Stylish dining set made from premium oak wood.",
//     details: ["Seating for 6", "Durable construction", "Natural oak finish"],
//     category: "Dining Room",
//   },
//   {
//     slug: "modern-wooden-chair-g",    name: "Rustic Bookshelf",
//     brand: "WoodWorks",
//     price: 260,
//     image: "/assets/chair4.png",
//     images: ["/assets/chair4.png", "/assets/chair5.png"],
//     description: "Rustic wooden bookshelf to store all your favorite books.",
//     details: ["Solid wood", "5 shelves", "Easy assembly"],
//     category: "Office",
//   },
//   {
//     slug: "modern-wooden-chair-h",    name: "Scandinavian Armchair",
//     brand: "NordCraft",
//     price: 190,
//     image: "/assets/chair1.jpg",
//     images: ["/assets/chair1.jpg", "/assets/chair2.jpg"],
//     description: "Minimalist Scandinavian armchair with comfort and style.",
//     details: ["Light wood frame", "Cushioned seat", "Modern design"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-i",    name: "Luxury Recliner Sofa",
//     brand: "ComfortHaus",
//     price: 850,
//     oldPrice: 950,
//     image: "/assets/chair10.jpg",
//     images: ["/assets/chair10.jpg", "/assets/chair11.jpg"],
//     description: "Relax in style with this luxury recliner sofa.",
//     details: ["Leather upholstery", "Adjustable recline", "Seating for 2"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-j",    name: "Glass Center Table",
//     brand: "Urban Edge",
//     price: 275,
//     image: "/assets/chair9.jpg",
//     images: ["/assets/chair9.jpg", "/assets/chair10.jpg"],
//     description: "Modern glass coffee table for your living area.",
//     details: ["Tempered glass", "Metal frame", "Easy to clean"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-k",
//     name: "Velvet Accent Chair",
//     brand: "LuxHome",
//     price: 310,
//     image: "/assets/chair8.jpg",
//     images: ["/assets/chair8.jpg", "/assets/chair9.jpg"],
//     description: "Chic velvet accent chair to complement any room.",
//     details: ["Soft velvet", "Comfortable padding", "Sturdy legs"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-l",
//     name: "Round Dining Table",
//     brand: "OakLine",
//     price: 450,
//     image: "/assets/chair4.jpg",
//     images: ["/assets/chair4.jpg", "/assets/chair5.jpg"],
//     description: "Elegant round dining table for family meals.",
//     details: ["Seating for 4", "Oak wood", "Smooth finish"],
//     category: "Dining Room",
//   },
//   {
//     slug: "modern-wooden-chair-m",
//     name: "Wooden TV Stand",
//     brand: "WoodWorks",
//     price: 330,
//     image: "/assets/chair4.png",
//     images: ["/assets/chair4.png", "/assets/chair5.png"],
//     description: "Classic wooden TV stand with storage space.",
//     details: ["Holds up to 50-inch TV", "3 storage compartments", "Solid wood"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-n",
//     name: "Minimalist Study Desk",
//     brand: "Urban Edge",
//     price: 210,
//     image: "/assets/chair9.jpg",
//     images: ["/assets/chair9.jpg", "/assets/chair10.jpg"],
//     description: "Sleek minimalist desk for your home office.",
//     details: ["Spacious tabletop", "Cable management", "Lightweight frame"],
//     category: "Office",
//   },
//   {
//     slug: "modern-wooden-chairo",
//     name: "Compact Shoe Rack",
//     brand: "WoodWorks",
//     price: 160,
//     image: "/assets/chair4.png",
//     images: ["/assets/chair4.png", "/assets/chair5.png"],
//     description: "Keep your shoes organized with this compact rack.",
//     details: ["3 shelves", "Sturdy design", "Easy assembly"],
//     category: "Bedroom",
//   },
//   {
//     slug: "modern-wooden-chair-p",
//     name: "Soft Lounge Ottoman",
//     brand: "LuxHome",
//     price: 180,
//     image: "/assets/chair8.jpg",
//     images: ["/assets/chair8.jpg", "/assets/chair9.jpg"],
//     description: "Comfortable ottoman for lounging or extra seating.",
//     details: ["Soft padding", "Sturdy legs", "Durable fabric"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-q",
//     name: "Modern Office Desk",
//     brand: "NordCraft",
//     price: 420,
//     image: "/assets/chair4.jpg",
//     images: ["/assets/chair4.jpg", "/assets/chair5.jpg"],
//     description: "Functional desk with modern design for office work.",
//     details: ["Spacious workspace", "Cable management", "Sturdy frame"],
//     category: "Office",
//   },
//   {
//     slug: "modern-wooden-chair-r",
//     name: "Kids Study Chair",
//     brand: "NordCraft",
//     price: 80,
//     image: "/assets/chair1.jpg",
//     images: ["/assets/chair1.jpg", "/assets/chair2.jpg"],
//     description: "Comfortable chair for kids' study or play area.",
//     details: ["Lightweight", "Durable material", "Fun design"],
//     category: "Kids Room",
//   },
//   {
//     slug: "modern-wooden-chair-s",
//     name: "Outdoor Patio Set",
//     brand: "ComfortHaus",
//     price: 560,
//     image: "/assets/chair10.jpg",
//     images: ["/assets/chair10.jpg", "/assets/chair11.jpg"],
//     description: "Perfect outdoor set for garden or patio relaxation.",
//     details: ["Weather-resistant", "Seating for 4", "Durable material"],
//     category: "Outdoor",
//   },
//   {
//     slug: "modern-wooden-chair-t",
//     name: "Two-Tier Coffee Table",
//     brand: "Urban Edge",
//     price: 250,
//     image: "/assets/chair9.jpg",
//     images: ["/assets/chair9.jpg", "/assets/chair10.jpg"],
//     description: "Practical coffee table with two-tier storage.",
//     details: ["Tempered glass", "Metal frame", "Modern design"],
//     category: "Living Room",
//   },
//   {
//     slug: "modern-wooden-chair-u",
//     name: "Upholstered Nightstand",
//     brand: "LuxHome",
//     price: 140,
//     image: "/assets/chair8.jpg",
//     images: ["/assets/chair8.jpg", "/assets/chair9.jpg"],
//     description: "Compact nightstand with soft upholstered finish.",
//     details: ["1 drawer", "Easy to clean", "Sturdy construction"],
//     category: "Bedroom",
//   },
// ];
