export interface Product {
  id: number;
  name: string;
  brand: string;
  price: number;
  oldPrice?: number;
  image: string;
  description: string;
  details: string[];
  images: string[];
}

export const products: Product[] = [
  {
    id: 1,
    name: "Modern Wooden Chair",
    brand: "OakLine",
    price: 120,
    image: "/assets/chair1.jpg",
    description: "A modern wooden chair crafted with precision and durability. Perfect for dining or study areas.",
    details: ["High-quality oak wood", "Ergonomic backrest", "Durable and easy to clean", "Modern design"],
    images: ["/assets/chair1.jpg", "/assets/chair2.jpg", "/assets/chair3.jpg", "/assets/chair4.jpg"],
  },
  {
    id: 2,
    name: "Classic Leather Sofa",
    brand: "ComfortHaus",
    price: 540,
    image: "/assets/chair10.jpg",
    description: "Premium comfort sofa with timeless leather design. Seats 3 people comfortably.",
    details: ["Genuine leather", "High-density foam cushions", "Strong wooden frame", "Timeless style"],
    images: ["/assets/chair10.jpg", "/assets/chair9.jpg", "/assets/chair8.jpg", "/assets/chair1.jpg"],
  },
  {
    id: 3,
    name: "Marble Coffee Table",
    brand: "Urban Edge",
    price: 230,
    image: "/assets/chair9.jpg",
    description: "Luxurious marble coffee table with sleek design for modern living rooms.",
    details: ["Natural marble top", "Stainless steel legs", "Scratch-resistant", "Elegant and minimalist"],
    images: ["/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair8.jpg", "/assets/chair10.jpg"],
  },
  {
    id: 4,
    name: "Velvet Lounge Chair",
    brand: "LuxHome",
    price: 320,
    oldPrice: 400,
    image: "/assets/chair8.jpg",
    description: "Velvet lounge chair perfect for relaxation or as a statement piece.",
    details: ["Soft velvet upholstery", "Gold-plated legs", "Contoured cushioning", "Modern design"],
    images: ["/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair10.jpg", "/assets/chair1.jpg"],
  },
  {
    id: 5,
    name: "Oak Dining Set",
    brand: "NordCraft",
    price: 780,
    image: "/assets/chair4.jpg",
    description: "Premium oak dining set for family gatherings with durability and style.",
    details: ["Solid oak", "Seats six", "Water-resistant finish", "Classic-modern appeal"],
    images: ["/assets/chair4.jpg", "/assets/chair3.jpg", "/assets/chair1.jpg", "/assets/chair10.jpg"],
  },
  {
    id: 6,
    name: "Rustic Bookshelf",
    brand: "WoodWorks",
    price: 260,
    image: "/assets/chair4.png",
    description: "Rustic bookshelf perfect for displaying books and décor.",
    details: ["Five-tier shelves", "Reclaimed wood", "Metal frame", "Eco-friendly materials"],
    images: ["/assets/chair4.png", "/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair10.jpg"],
  },
  {
    id: 7,
    name: "Scandinavian Armchair",
    brand: "NordCraft",
    price: 190,
    image: "/assets/chair1.jpg",
    description: "Minimalist Scandinavian armchair with cozy design for modern interiors.",
    details: ["Linen fabric", "Solid wood legs", "Lightweight", "Durable and stylish"],
    images: ["/assets/chair1.jpg", "/assets/chair2.jpg", "/assets/chair3.jpg", "/assets/chair8.jpg"],
  },
  {
    id: 8,
    name: "Luxury Recliner Sofa",
    brand: "ComfortHaus",
    price: 850,
    oldPrice: 950,
    image: "/assets/chair10.jpg",
    description: "Luxury recliner sofa with plush cushioning and smooth reclining features.",
    details: ["Automatic recline", "Premium leather", "2-seater design", "High back support"],
    images: ["/assets/chair10.jpg", "/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair1.jpg"],
  },
  {
    id: 9,
    name: "Glass Center Table",
    brand: "Urban Edge",
    price: 275,
    image: "/assets/chair9.jpg",
    description: "Sleek glass center table perfect for modern living room setups.",
    details: ["Tempered glass", "Chrome base", "Lightweight", "Scratch-resistant"],
    images: ["/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair8.jpg", "/assets/chair1.jpg"],
  },
  {
    id: 10,
    name: "Velvet Accent Chair",
    brand: "LuxHome",
    price: 310,
    image: "/assets/chair8.jpg",
    description: "Luxurious velvet accent chair to elevate any interior space.",
    details: ["Velvet upholstery", "Compact design", "Foam-filled", "Easy assembly"],
    images: ["/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair10.jpg"],
  },
  {
    id: 11,
    name: "Round Dining Table",
    brand: "OakLine",
    price: 450,
    image: "/assets/chair4.jpg",
    description: "Round oak dining table ideal for intimate meals or modern spaces.",
    details: ["Solid oak", "Smooth finish", "Seats 4-6 people", "Sturdy legs"],
    images: ["/assets/chair4.jpg", "/assets/chair1.jpg", "/assets/chair2.jpg", "/assets/chair3.jpg"],
  },
  {
    id: 12,
    name: "Wooden TV Stand",
    brand: "WoodWorks",
    price: 330,
    image: "/assets/chair4.png",
    description: "Rustic wooden TV stand with ample storage for media devices.",
    details: ["Reclaimed wood", "Open shelves and drawers", "Durable frame", "Natural finish"],
    images: ["/assets/chair4.png", "/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair10.jpg"],
  },
  {
    id: 13,
    name: "Minimalist Study Desk",
    brand: "Urban Edge",
    price: 210,
    image: "/assets/chair9.jpg",
    description: "Minimalist study desk designed for productivity and style.",
    details: ["Smooth surface", "Lightweight design", "Sturdy legs", "Space for laptop and books"],
    images: ["/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair1.jpg", "/assets/chair8.jpg"],
  },
  {
    id: 14,
    name: "Upholstered Bed Frame",
    brand: "LuxHome",
    price: 990,
    image: "/assets/chair8.jpg",
    description: "Elegant upholstered bed frame designed for comfort and style.",
    details: ["Soft fabric", "Sturdy wooden base", "Easy assembly", "Available in multiple sizes"],
    images: ["/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair10.jpg"],
  },
  {
    id: 15,
    name: "Compact Shoe Rack",
    brand: "WoodWorks",
    price: 160,
    image: "/assets/chair4.png",
    description: "Space-saving shoe rack perfect for small apartments or closets.",
    details: ["3-tier storage", "Solid wood frame", "Lightweight", "Easy to assemble"],
    images: ["/assets/chair4.png", "/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair10.jpg"],
  },
  {
    id: 16,
    name: "Classic Dining Chair",
    brand: "OakLine",
    price: 140,
    image: "/assets/chair1.jpg",
    description: "Classic oak dining chair with ergonomic design and timeless appeal.",
    details: ["Solid oak", "Curved backrest", "Durable finish", "Comfortable seating"],
    images: ["/assets/chair1.jpg", "/assets/chair2.jpg", "/assets/chair3.jpg", "/assets/chair4.jpg"],
  },
  {
    id: 17,
    name: "Contemporary Sectional Sofa",
    brand: "ComfortHaus",
    price: 1100,
    oldPrice: 1250,
    image: "/assets/chair10.jpg",
    description: "Large contemporary sectional sofa combining comfort, style, and functionality.",
    details: ["Modular design", "Premium leather", "Seats 5-6 people", "Durable frame"],
    images: ["/assets/chair10.jpg", "/assets/chair9.jpg", "/assets/chair8.jpg", "/assets/chair1.jpg"],
  },
  {
    id: 18,
    name: "Modern Office Desk",
    brand: "NordCraft",
    price: 420,
    image: "/assets/chair4.jpg",
    description: "Sleek office desk with minimalist design for modern workspaces.",
    details: ["Spacious surface", "Cable management", "Sturdy construction", "Stylish finish"],
    images: ["/assets/chair4.jpg", "/assets/chair1.jpg", "/assets/chair2.jpg", "/assets/chair3.jpg"],
  },
  {
    id: 19,
    name: "Two-Tier Coffee Table",
    brand: "Urban Edge",
    price: 250,
    image: "/assets/chair9.jpg",
    description: "Functional two-tier coffee table providing extra storage and modern style.",
    details: ["Tempered glass top", "Lower shelf storage", "Sturdy metal legs", "Elegant finish"],
    images: ["/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair8.jpg", "/assets/chair1.jpg"],
  },
  {
    id: 20,
    name: "Soft Lounge Ottoman",
    brand: "LuxHome",
    price: 180,
    image: "/assets/chair8.jpg",
    description: "Soft lounge ottoman for ultimate comfort and versatile usage in living areas.",
    details: ["Velvet upholstery", "Foam-filled cushion", "Lightweight", "Perfect for feet or seating"],
    images: ["/assets/chair8.jpg", "/assets/chair9.jpg", "/assets/chair4.jpg", "/assets/chair10.jpg"],
  },
];
